### ISSUE TITLE
Bows useless with offhand items

### ISSUE THREAD

**Issue by stubkan** [tr7zw/FirstPersonModel-Fabric#48]
Its a major problem, because on survival servers it is a priority to have a totem in your offhand all the time.

Bows and crossbows are unusable like this, as the totem (or whatever item you have offhand) blocks your entire view point when you aim with them.

**Comment by tr7zw** [comment]
Added a fix that will be in the next release to hide the other item while pulling a bow.

**Comment by stubkan** [comment]
Brilliant :+1: 

Thank you very much

**Comment by tr7zw** [comment]
But as an FYI: the next release is going to be a 2.0 Version with tons of new features like cosmetics/custom player size/redone config/multiplayer cosmetic sync/3d skin layers etc. so it will take some time till it's done and released(Also couldn't even release right now if I wanted to because of the CurseForge owner transfer my account is currently stuck in limbo for the next few days https://www.curseforge.com/minecraft/mc-mods/first-person-model). You can download the in-dev nightly builds from the Actions tab if you want the fixes/features sooner and give feedback via Discord/Issues 😃.

**Comment by stubkan** [comment]
I have been using in-dev for now with bows, I see no issues, its working great.  There is a similar separate issue with crossbows however, so a similar removal of offhand items while wielding a crossbow would be good I think.
